# @package _group_
lapa:
  root_dir: 'data/LaPa'

  train:
    use_factor: 0.01  # What percentage of the dataset to use

  val:
    use_factor: 0.1  # What percentage of the dataset to use

  test:
    use_factor: 0.1  # What percentage of the dataset to use
